spring.application.name=document-processor

#spring.profiles.active=local
#Switch the active profile from local to aws
spring.profiles.active=aws

# Non-secret AWS Configuration
aws.s3.bucket.name=document-processor-upload-files-2026
aws.region=ap-south-1
